#!/usr/bin/env bash

if [ -f /etc/yadm/bootstrap-config ]; then
    source /etc/yadm/bootstrap-config
fi

while [ -z "$YADM_HOSTNAME" ]; do
    echo -n "Enter the hostname (without domain) for this system: "
    read -r YADM_HOSTNAME
done

if [ -z "$YADM_DOMAIN" ]; then
    echo -n "Enter the domain for this system: "
    read -r YADM_DOMAIN
fi

if [ -z "$YADM_USERNAME" ]; then
    echo -n "Enter the username for the main non-root user: "
    read -r YADM_USERNAME
fi

cat > /etc/yadm/bootstrap-config << EOF
export YADM_HOSTNAME="$YADM_HOSTNAME"
export YADM_DOMAIN="$YADM_DOMAIN"
export YADM_USERNAME="$YADM_USERNAME"
EOF

# Set the time zone and hardware clock
ln -sf /usr/share/zoneinfo/US/Eastern /etc/localtime
hwclock --systohc

# Generate locales
locale-gen

# Configure the hostname
echo "$YADM_HOSTNAME" > /etc/hostname

# Add matching entries to `/etc/hosts`
cat > /etc/hosts << EOF
127.0.0.1   localhost
::1         localhost
127.0.0.1   $YADM_HOSTNAME.$YADM_DOMAIN $YADM_HOSTNAME
EOF

# Use traditional interface names (eth0, wlan0, etc...)
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# Import and trust personal key used to build custom packages
curl https://pkg.stiles.dev/archlinux.gpg | pacman-key --add -
pacman-key --finger 071717CF
pacman-key --lsign 071717CF
pacman -Sy

# Set up boot manager
bootctl --path=/boot install

cat > /boot/loader/entries/arch.conf << EOF
title	Arch Linux
linux 	/vmlinuz-linux
initrd  /initramfs-linux.img
options root=$(mount | grep "on / " | cut -s -d ' ' -f 1) rootfstype=ext4 zswap.enabled=0 rw add_efi_memmap
EOF

cat > /boot/loader/loader.conf << EOF
default arch
timeout 1
editor 1
EOF

# Set root password
echo "Setting password for root"
passwd

# Grant sudo priviledges to the 'wheel' group
#echo "%wheel ALL=(ALL) ALL" > /etc/sudoers.d/10-install

# Create a user account with sudo priviledges
useradd -m -G wheel "$YADM_USERNAME"
echo "Setting password for $YADM_USERNAME"
passwd "$YADM_USERNAME"

echo "Enabling NetworkManager.service"
systemctl enable NetworkManager.service
