#!/usr/bin/env bash

if [ -f /etc/yadm/bootstrap-config ]; then
    source /etc/yadm/bootstrap-config
fi

while [ -z "$YADM_HOSTNAME" ]; do
    echo -n "Enter the hostname for this system: "
    read -r YADM_HOSTNAME
done

if [ -z "$YADM_DOMAIN" ]; then
    echo -n "Enter the domain for this system: "
    read -r YADM_DOMAIN
fi

if [ -z "$YADM_USERNAME" ]; then
    echo -n "Enter the username for the main non-root user: "
    read -r YADM_USERNAME
fi

cat > /etc/yadm/bootstrap-config << EOF
export YADM_HOSTNAME="$YADM_HOSTNAME"
export YADM_DOMAIN="$YADM_DOMAIN"
export YADM_USERNAME="$YADM_USERNAME"
EOF

# Set the time zone and hardware clock
ln -sf /usr/share/zoneinfo/US/Eastern /etc/localtime
timedatectl set-ntp true
hwclock --systohc

# Configure localization
sed -i "s/^\#\(en_US\.UTF\-8.*$\)/\1/" /etc/locale.gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
locale-gen

# Configure the hostname
echo "$HOSTNAME" > /etc/hostname

# Add matching entries to `/etc/hosts`
cat > /etc/hosts << EOF
127.0.0.1   localhost
::1         localhost
127.0.0.1   $HOSTNAME.$DOMAIN $HOSTNAME
EOF

# Use traditional interface names (eth0, wlan0, etc...)
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# Install wifi-menu dependencies (only needed if wifi-menu will be used to configure wireless connections on the installed system)
pacman -S dialog wpa_supplicant

# Install Intel microcode updates
pacman -Syu intel-ucode

# Set up boot manager
bootctl --path=/boot install

cat > /boot/loader/entries/arch.conf << EOF
title	Arch Linux
linux 	/vmlinuz-linux
initrd  /initramfs-linux.img
options root=$(mount | grep "on / " | cut -s -d ' ' -f 1) rootfstype=ext4 rw add_efi_memmap
EOF

cat > /boot/loader/loader.conf << EOF
default arch
timeout 1
editor 1
EOF

# Set root password
echo "Setting password for root"
passwd

# Grant sudo priviledges to the 'wheel' group
#echo "%wheel ALL=(ALL) ALL" > /etc/sudoers.d/10-install

# Create a user account with sudo priviledges
useradd -m -G wheel "$USERNAME"
echo "Setting password for $USERNAME"
passwd "$USERNAME"

