#!/usr/bin/env bash

PKG_PACSTRAP=(
    base
    base-devel
    linux
    linux-firmware
    man-db
    man-pages
    inetutils
    networkmanager
    wpa_supplicant
    openssh
    git
    yadm
    neovim
)

case $(lscpu | grep "Vendor ID") in
*AuthenticAMD)
    PKG_PACSTRAP+=(amd-ucode)
    ;;
*GenuineIntel)
    PKG_PACSTRAP+=(intel-ucode)
    ;;
esac

PKG_PACSTRAP="${PKG_PACSTRAP[@]}"

sourced=false
if [ -n "$ZSH_VERSION" ]; then
    case $ZSH_EVAL_CONTEXT in *:file) sourced=true;; esac
elif [ -n "$BASH_VERSION" ]; then
    (return 0 2>/dev/null) && sourced=true
else
    case ${0##*/} in sh|-sh) sourced=true;; esac
fi

if $sourced; then
    export PKG_PACSTRAP
    return
fi


# Update the system clock
timedatectl set-ntp true
timedatectl status

# Download a current pacman mirror list
reflector --country US --delay 1 --protocol https --fastest 10 --save /etc/pacman.d/mirrorlist

# Install base packages
pacstrap /mnt "$PKG_PACSTRAP"

# Generate fstab file
genfstab -U /mnt >> /mnt/etc/fstab

echo "fstab generated for new system:"
cat /mnt/etc/fstab

echo "If this appears to be correct for your partition scheme, next run 'arch-chroot /mnt'"

