#!/usr/bin/env bash

# Update the system clock
timedatectl set-ntp true
timedatectl status

# Download a current pacman mirror list
reflector --country US --delay 1 --protocol https --fastest 10 --save /etc/pacman.d/mirrorlist

# Install base packages
pacstrap /mnt base base-devel linux linux-firmware dhcpcd openresolv inetutils man-db man-pages netctl openssh vim git yadm

# Generate fstab file
genfstab -U /mnt >> /mnt/etc/fstab

echo "fstab generated for new system:"
cat /mnt/etc/fstab

echo "If this appears to be correct for your partition scheme, next run 'arch-chroot /mnt'"

